"""add destination_url to event_delivery

Revision ID: 05668f8ded74
Revises: 37061020dee0
Create Date: 2026-05-22 21:23:41.850153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05668f8ded74'
down_revision: Union[str, Sequence[str], None] = '37061020dee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_delivery', sa.Column('destination_url', sa.String(length=1000), nullable=True))
    op.drop_constraint(op.f('event_delivery_event_id_fkey'), 'event_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'event_delivery', 'event', ['event_id'], ['id'], source_schema='outbox', referent_schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_delivery', schema='outbox', type_='foreignkey')
    op.create_foreign_key(op.f('event_delivery_event_id_fkey'), 'event_delivery', 'event', ['event_id'], ['id'])
    op.drop_column('event_delivery', 'destination_url')
    # ### end Alembic commands ###
