"""Added admin API and metrics basis

Revision ID: 1165a7627178
Revises: f78cb8dfcc24
Create Date: 2026-05-24 15:44:40.395212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1165a7627178'
down_revision: Union[str, Sequence[str], None] = 'f78cb8dfcc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type_id', sa.BigInteger(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_code', 'project_id', 'event_type_id', 'period_start', 'period_end', name='uq_system_metric_period'),
    schema='outbox'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_metric', schema='outbox')
    # ### end Alembic commands ###
