"""add auth models

Revision ID: 2c0d844c5aca
Revises: 88391a903eb5
Create Date: 2026-05-27 14:37:13.471649

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c0d844c5aca'
down_revision: Union[str, Sequence[str], None] = '88391a903eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role', schema='outbox'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_user_account_email'), 'user_account', ['email'], unique=True, schema='outbox')
    op.create_index(op.f('ix_outbox_user_account_id'), 'user_account', ['id'], unique=False, schema='outbox')
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_api_key_id'), 'api_key', ['id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_api_key_key_prefix'), 'api_key', ['key_prefix'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_api_key_project_id'), 'api_key', ['project_id'], unique=False, schema='outbox')
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'DEVELOPER', 'VIEWER', name='project_member_role', schema='outbox'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['outbox.user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_project_user'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_project_member_id'), 'project_member', ['id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_project_member_project_id'), 'project_member', ['project_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_project_member_user_id'), 'project_member', ['user_id'], unique=False, schema='outbox')
    op.create_table('metrics_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_metrics_token_event_type_id'), 'metrics_token', ['event_type_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metrics_token_id'), 'metrics_token', ['id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metrics_token_project_id'), 'metrics_token', ['project_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metrics_token_token_prefix'), 'metrics_token', ['token_prefix'], unique=False, schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_outbox_metrics_token_token_prefix"),
        table_name="metrics_token",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_metrics_token_project_id"),
        table_name="metrics_token",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_metrics_token_id"),
        table_name="metrics_token",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_metrics_token_event_type_id"),
        table_name="metrics_token",
        schema="outbox",
    )
    op.drop_table("metrics_token", schema="outbox")

    op.drop_index(
        op.f("ix_outbox_project_member_user_id"),
        table_name="project_member",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_project_member_project_id"),
        table_name="project_member",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_project_member_id"),
        table_name="project_member",
        schema="outbox",
    )
    op.drop_table("project_member", schema="outbox")

    op.drop_index(
        op.f("ix_outbox_api_key_project_id"),
        table_name="api_key",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_api_key_key_prefix"),
        table_name="api_key",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_api_key_id"),
        table_name="api_key",
        schema="outbox",
    )
    op.drop_table("api_key", schema="outbox")

    op.drop_index(
        op.f("ix_outbox_user_account_id"),
        table_name="user_account",
        schema="outbox",
    )
    op.drop_index(
        op.f("ix_outbox_user_account_email"),
        table_name="user_account",
        schema="outbox",
    )
    op.drop_table("user_account", schema="outbox")
