"""add processing chains and plans

Revision ID: 347082a348b9
Revises: bac43b170f88
Create Date: 2026-06-03 14:29:16.536612

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '347082a348b9'
down_revision: Union[str, Sequence[str], None] = 'bac43b170f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('processing_chain',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('schema_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.ForeignKeyConstraint(['schema_definition_id'], ['outbox.schema_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'schema_definition_id', 'version_number', name='uq_processing_chain_scope_version'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_processing_chain_event_type_id'), 'processing_chain', ['event_type_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_processing_chain_schema_definition_id'), 'processing_chain', ['schema_definition_id'], unique=False, schema='outbox')
    op.create_table('processing_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('processing_chain_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_version_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['outbox.metric_definition.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_version_id'], ['outbox.metric_definition_version.id'], ),
    sa.ForeignKeyConstraint(['processing_chain_id'], ['outbox.processing_chain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_chain_id', 'metric_definition_id', name='uq_processing_plan_chain_metric_definition'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_processing_plan_metric_definition_id'), 'processing_plan', ['metric_definition_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_processing_plan_metric_definition_version_id'), 'processing_plan', ['metric_definition_version_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_processing_plan_processing_chain_id'), 'processing_plan', ['processing_chain_id'], unique=False, schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_processing_plan_processing_chain_id'), table_name='processing_plan', schema='outbox')
    op.drop_index(op.f('ix_outbox_processing_plan_metric_definition_version_id'), table_name='processing_plan', schema='outbox')
    op.drop_index(op.f('ix_outbox_processing_plan_metric_definition_id'), table_name='processing_plan', schema='outbox')
    op.drop_table('processing_plan', schema='outbox')
    op.drop_index(op.f('ix_outbox_processing_chain_schema_definition_id'), table_name='processing_chain', schema='outbox')
    op.drop_index(op.f('ix_outbox_processing_chain_event_type_id'), table_name='processing_chain', schema='outbox')
    op.drop_table('processing_chain', schema='outbox')
    # ### end Alembic commands ###
