"""add analytical observations

Revision ID: 4de751cd9de2
Revises: b9f60c323a1f
Create Date: 2026-06-02 15:56:13.348877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4de751cd9de2'
down_revision: Union[str, Sequence[str], None] = 'b9f60c323a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytical_observation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_version_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_code', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbox.event.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['outbox.metric_definition.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_version_id'], ['outbox.metric_definition_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    op.create_index('ix_analytical_observation_project_event_type_metric_observed_at', 'analytical_observation', ['project_id', 'event_type_id', 'metric_code', 'observed_at'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_event_id'), 'analytical_observation', ['event_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_event_type_id'), 'analytical_observation', ['event_type_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_metric_code'), 'analytical_observation', ['metric_code'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_metric_definition_id'), 'analytical_observation', ['metric_definition_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_metric_definition_version_id'), 'analytical_observation', ['metric_definition_version_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_observed_at'), 'analytical_observation', ['observed_at'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_analytical_observation_project_id'), 'analytical_observation', ['project_id'], unique=False, schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_analytical_observation_project_id'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_observed_at'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_metric_definition_version_id'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_metric_definition_id'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_metric_code'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_event_type_id'), table_name='analytical_observation', schema='outbox')
    op.drop_index(op.f('ix_outbox_analytical_observation_event_id'), table_name='analytical_observation', schema='outbox')
    op.drop_index('ix_analytical_observation_project_event_type_metric_observed_at', table_name='analytical_observation', schema='outbox')
    op.drop_table('analytical_observation', schema='outbox')
    # ### end Alembic commands ###
