"""add metric state and checkpoint

Revision ID: 8cd8381d1f4d
Revises: f6e6b51d5685
Create Date: 2026-06-22 17:45:28.975006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cd8381d1f4d'
down_revision: Union[str, Sequence[str], None] = 'f6e6b51d5685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_checkpoint',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checkpoint_name', sa.String(length=100), nullable=False),
    sa.Column('last_processed_observation_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_name', name='uq_metric_checkpoint_name'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_metric_checkpoint_checkpoint_name'), 'metric_checkpoint', ['checkpoint_name'], unique=False, schema='outbox')
    op.create_table('metric_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_definition_version_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_code', sa.String(length=150), nullable=False),
    sa.Column('labels_hash', sa.String(length=64), nullable=False),
    sa.Column('labels_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['outbox.metric_definition.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_version_id'], ['outbox.metric_definition_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_type_id', 'metric_code', 'labels_hash', name='uq_metric_state_series'),
    schema='outbox'
    )
    op.create_index('ix_metric_state_project_event_type_metric', 'metric_state', ['project_id', 'event_type_id', 'metric_code'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_event_type_id'), 'metric_state', ['event_type_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_labels_hash'), 'metric_state', ['labels_hash'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_metric_code'), 'metric_state', ['metric_code'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_metric_definition_id'), 'metric_state', ['metric_definition_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_metric_definition_version_id'), 'metric_state', ['metric_definition_version_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_state_project_id'), 'metric_state', ['project_id'], unique=False, schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_metric_state_project_id'), table_name='metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_state_metric_definition_version_id'), table_name='metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_state_metric_definition_id'), table_name='metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_state_metric_code'), table_name='metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_state_labels_hash'), table_name='metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_state_event_type_id'), table_name='metric_state', schema='outbox')
    op.drop_index('ix_metric_state_project_event_type_metric', table_name='metric_state', schema='outbox')
    op.drop_table('metric_state', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_checkpoint_checkpoint_name'), table_name='metric_checkpoint', schema='outbox')
    op.drop_table('metric_checkpoint', schema='outbox')
    # ### end Alembic commands ###
