"""add metric definition versioning

Revision ID: b9f60c323a1f
Revises: 2c0d844c5aca
Create Date: 2026-05-31 18:07:47.991580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9f60c323a1f'
down_revision: Union[str, Sequence[str], None] = '2c0d844c5aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('metric_definition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'code', name='uq_metric_definition_event_type_code'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_metric_definition_event_type_id'), 'metric_definition', ['event_type_id'], unique=False, schema='outbox')
    op.create_table('metric_definition_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('yaml_version_client', sa.String(length=30), nullable=True),
    sa.Column('yaml_version_internal', sa.String(length=30), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['outbox.metric_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_definition_id', 'yaml_version_internal', name='uq_metric_definition_yaml_internal_version'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_metric_definition_version_metric_definition_id'), 'metric_definition_version', ['metric_definition_id'], unique=False, schema='outbox')
    op.create_table('metric_definition_version_schema',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_definition_version_id', sa.BigInteger(), nullable=False),
    sa.Column('schema_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_version_id'], ['outbox.metric_definition_version.id'], ),
    sa.ForeignKeyConstraint(['schema_definition_id'], ['outbox.schema_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_definition_version_id', 'schema_definition_id', name='uq_metric_definition_version_schema'),
    schema='outbox'
    )
    op.create_index(op.f('ix_outbox_metric_definition_version_schema_metric_definition_version_id'), 'metric_definition_version_schema', ['metric_definition_version_id'], unique=False, schema='outbox')
    op.create_index(op.f('ix_outbox_metric_definition_version_schema_schema_definition_id'), 'metric_definition_version_schema', ['schema_definition_id'], unique=False, schema='outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_metric_definition_version_schema_schema_definition_id'), table_name='metric_definition_version_schema', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_definition_version_schema_metric_definition_version_id'), table_name='metric_definition_version_schema', schema='outbox')
    op.drop_table('metric_definition_version_schema', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_definition_version_metric_definition_id'), table_name='metric_definition_version', schema='outbox')
    op.drop_table('metric_definition_version', schema='outbox')
    op.drop_index(op.f('ix_outbox_metric_definition_event_type_id'), table_name='metric_definition', schema='outbox')
    op.drop_table('metric_definition', schema='outbox')
    # ### end Alembic commands ###
