"""initial outbox schema

Revision ID: e143e4542c16
Revises: 
Create Date: 2026-05-25 18:14:45.147074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e143e4542c16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='outbox'
    )
    op.create_table('event_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_event_type_project_code'),
    schema='outbox'
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('json_version_internal', sa.String(length=30), server_default='1.0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid'),
    schema='outbox'
    )
    op.create_table('route_definition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('routing_key', sa.String(length=100), nullable=False),
    sa.Column('destination_name', sa.String(length=100), nullable=False),
    sa.Column('destination_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'routing_key', 'destination_url', name='uq_route_event_type_routing_destination'),
    schema='outbox'
    )
    op.create_table('schema_definition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.BigInteger(), nullable=False),
    sa.Column('json_version_client', sa.String(length=30), nullable=True),
    sa.Column('json_version_internal', sa.String(length=30), nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type_id', 'json_version_internal', name='uq_schema_event_type_internal_version'),
    schema='outbox'
    )
    op.create_table('system_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type_id', sa.BigInteger(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['outbox.event_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_code', 'project_id', 'event_type_id', 'period_start', 'period_end', name='uq_system_metric_period'),
    schema='outbox'
    )
    op.create_table('event_delivery',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_name', sa.String(length=150), nullable=False),
    sa.Column('destination_type', sa.String(length=50), nullable=False),
    sa.Column('destination_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbox.event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_delivery', schema='outbox')
    op.drop_table('system_metric', schema='outbox')
    op.drop_table('schema_definition', schema='outbox')
    op.drop_table('route_definition', schema='outbox')
    op.drop_table('event', schema='outbox')
    op.drop_table('event_type', schema='outbox')
    op.drop_table('project', schema='outbox')
    # ### end Alembic commands ###
