"""add event updated at

Revision ID: ea5f68a12cc1
Revises: b66396dc6b87
Create Date: 2026-05-22 16:44:42.363647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5f68a12cc1'
down_revision: Union[str, Sequence[str], None] = 'b66396dc6b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("""UPDATE event SET updated_at=created_at WHERE updated_at IS NULL""")

    op.alter_column(
        "event",
        "updated_at",
        nullable=False,
        schema="outbox",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('event', 'updated_at', schema="outbox")
    # ### end Alembic commands ###
