"""add all tables

Revision ID: f78cb8dfcc24
Revises: 799d2e93a401
Create Date: 2026-05-23 15:41:25.706289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f78cb8dfcc24'
down_revision: Union[str, Sequence[str], None] = '799d2e93a401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='outbox'
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='outbox'
    )
    op.create_table('event_delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(length=150), nullable=False),
    sa.Column('destination_type', sa.String(length=50), nullable=False),
    sa.Column('destination_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbox.event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    op.create_table('route_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('routing_key', sa.String(length=100), nullable=True),
    sa.Column('destination_name', sa.String(length=100), nullable=True),
    sa.Column('destination_url', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    op.create_table('schema_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['outbox.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='outbox'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_definition', schema='outbox')
    op.drop_table('route_definition', schema='outbox')
    op.drop_table('event_delivery', schema='outbox')
    op.drop_table('project', schema='outbox')
    op.drop_table('event', schema='outbox')
    # ### end Alembic commands ###
