from enum import StrEnum


class RuntimeEventType(StrEnum):
    """Runtime event categories emitted by the real OB1 pipeline."""

    WORKER_CYCLE_STARTED = "WORKER_CYCLE_STARTED"
    WORKER_CYCLE_FINISHED = "WORKER_CYCLE_FINISHED"

    METRICS_EXTRACTED = "METRICS_EXTRACTED"
    EVENT_ROUTED = "EVENT_ROUTED"
    EVENT_COMPLETED = "EVENT_COMPLETED"
    EVENT_UNROUTABLE = "EVENT_UNROUTABLE"
    EVENT_FAILED = "EVENT_FAILED"

    DELIVERY_STARTED = "DELIVERY_STARTED"
    DELIVERY_SUCCEEDED = "DELIVERY_SUCCEEDED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    DELIVERY_DEAD_LETTERED = "DELIVERY_DEAD_LETTERED"
    DEAD_LETTER_RETRY_REQUESTED = "DEAD_LETTER_RETRY_REQUESTED"